### ISSUE TITLE
5.0b still adds multiple UE4 entries.

### ISSUE THREAD

**Issue by DennoCoil** [JosefNemec/Playnite.Testing#16] opened 2019-06-12 20:02 UTC
I thought it was fixed in an earlier patch, but something must have regressed this.  Not a problem with the Hide function and very few will ever notice.
![2019-06-12 15_36_20-Playnite](https://user-images.githubusercontent.com/21137176/59382250-3b544780-8d2b-11e9-896f-09673050961a.png)

**Comment by JosefNemec** [comment] 2019-06-17 10:48
I can't reproduce it, can you please attach `c:\Users\All Users\Epic\UnrealEngineLauncher\LauncherInstalled.dat` file?

**Comment by JosefNemec** [comment] 2019-07-10 12:45
Closing since I haven't received requested file for further investigation.

**Closed by JosefNemec** 2019-07-10 12:45 UTC
